nginx:
  user: onpa
  group: tez-www-srejta
  connections: '87'
  multi_accept: '0'
  errorlog:
    file: pliczek.log
    style: styl-szmyl
  use: '1'
server:
  defaults:
    listen:
      port: '100'
