nginx:
  user: lolMAX
  group: tez-www-srejta
  connections: '87'
  multi_accept: '0'
  errorlog:
    file: pliczek.log
    style: styl-szmyl
server:
  defaults:
    listen:
      ip: 123.123.123.123
