nginx:
  user: www-data
  group: grupa
  connections: '8000'
  multi_accept: '1'
  errorlog:
    file: pliczek.log
    style: styl-szmyl
  use: drugi
  sendfile: on
  gzip:
    gzip: '0'
  max_body: '80'
  http:
    ignore_invalid_headers: on
    tokens: prod
  server:
    defaults:
      listen: 1000
