nginx:
  user: www-data
  group: www-data
  connections: '8000'
  multi_accept: '1'
  errorlog:
    file: pliczek.log
    style: styl-szmyl
  use: drugi
server:
  defaults:
    listen:
      port: '100'
