nginx:
  user: www-data
  group: www-data
  connections: 4096
  use: epoll
  multi_accept: 1
  errorlog:
    file: '/var/log/nginx/error.log'
    style: 'error'
  sendfile: 1
  nodelay: 1
  katimeout: 60
  http:
    ignore_invalid_headers: on
    tokens: off
    max_body: 1024m
  server:
    defaults:
      listen: 80
      gzip:
        vary: 1
      index: index.html index.htm
      drop: FIX_ME #TODO
      staticexpire: FIX_ME #TODO
      php: FIX_ME #TODO
      simplerewrite: FIX_ME #TODO
      support:
        drop: on
        gzip: on
        staticexpire: on